version: 0.2

# ========================================================
# 0. 환경 변수 설정 (중앙 관리)
# ========================================================
env:
  variables:
    AWS_REGION: "ap-northeast-2"          # AWS 리전 (서울: ap-northeast-2)
    AWS_ACCOUNT_ID: "640107381732"       # AWS 12자리 계정 ID
    ECR_REPO_NAME: "gmst-green-repo"       # 이미지를 저장할 ECR 리포지토리 이름
    GITHUB_USER: "hnmly"                  # GitHub 사용자명/조직명
    TARGET_REPO: "wskd1-green"            # 배포용 매니페스트가 있는 리포지토리
    TARGET_BRANCH: "main"                # 업데이트를 푸시할 브랜치
    TARGET_FILE: "green.yaml"             # 이미지 태그를 교체할 YAML 파일명
       # GitHub Personal Access Token (직접 입력 시)

phases:
  # ========================================================
  # 1. Install 단계: 도구 설치
  # ========================================================
  install:
    commands:
      - echo "Installing tools..."
      - yum install -y jq git            # JSON 파싱용 jq와 버전 관리용 git 설치

  # ========================================================
  # 2. Pre_build 단계: 로그인 및 준비
  # ========================================================
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      # ECR에 Docker 이미지를 푸시하기 위한 인증 토큰 획득 및 로그인
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  # ========================================================
  # 3. Build 단계: 이미지 생성 및 태깅
  # ========================================================
  build:
    commands:
      - echo "Building Docker image..."
      # 한국 시간 기준 현재 날짜/시간으로 고유한 이미지 태그 생성
      - export IMAGE_TAG=$(TZ="Asia/Seoul" date +"%Y-%m-%d.%H.%M.%S")
      # 나중에 참조할 수 있도록 태그를 파일로 저장
      - echo "IMAGE_TAG=$IMAGE_TAG" | tee image_tag.txt
      # ECR 풀 경로 생성 (계정ID.dkr.ecr.리전.amazonaws.com/리포지토리:태그)
      - export IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG"
      # Dockerfile을 사용하여 이미지 빌드
      - docker build -t "$IMAGE_URI" $CODEBUILD_SRC_DIR/image

  # ========================================================
  # 4. Post_build 단계: 이미지 푸시 및 GitOps 업데이트
  # ========================================================
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      # 빌드된 이미지를 AWS ECR 리포지토리로 업로드
      - docker push "$IMAGE_URI"
      
      - echo "Generating imageDetail.json for ECS..."
      # ECS 배포 단계에서 인식할 수 있는 이미지 정보 파일 생성
      - printf '{"ImageURI":"%s"}' "$IMAGE_URI" > imageDetail.json

      - echo "Cloning manifest repository..."
      # GitOps를 위해 설정용 리포지토리를 클론 (Token 인증 방식)
      - git clone -b $TARGET_BRANCH https://$TOKEN@github.com/$GITHUB_USER/$TARGET_REPO.git repo2
      - cd repo2

      - echo "Updating image tag in $TARGET_FILE..."
      # sed 명령어로 YAML 파일 내의 'image:' 뒷부분을 새로운 IMAGE_URI로 자동 교체
      - sed -i "s|image: .*|image: $IMAGE_URI|" $TARGET_FILE

      - echo "Committing and pushing changes to GitHub..."
      # Git 커밋을 위한 작성자 정보 설정
      - git config --global user.email "codebuild@build.com"
      - git config --global user.name "codebuild-bot"
      # 변경 사항 스테이징 및 커밋
      - git add $TARGET_FILE
      - git commit -m "Auto update image to $IMAGE_TAG [skip ci]"
      # 설정 리포지토리에 푸시 (ArgoCD 등이 이 변경사항을 감지하여 자동 배포함)
      - git push origin $TARGET_BRANCH

# ========================================================
# Artifacts: 다음 파이프라인 단계로 전달할 결과물
# ========================================================
artifacts:
  files:
    - imageDetail.json    # ECS 배포 도구용
    - image_tag.txt       # 빌드 기록 및 디버깅용
